## Install Selenium through pip:
Before import webdriver we have to install selenium.

In [ ]:
!pip install selenium

### check selenium version in jupyter notebook :

In [1]:
pip show selenium

Name: selenium
Version: 4.3.0
Summary:
Home-page: https://www.selenium.dev
Author:
Author-email:
License: Apache 2.0
Location: c:\users\user\anaconda3\lib\site-packages
Requires: trio, urllib3, trio-websocket
Required-by:
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -ffi (c:\users\user\anaconda3\lib\site-packages)

## Import the necessary library for web scraping:

In [2]:
from selenium import webdriver
import time
import pandas as pd

### Setup Selenium Web-Driver:
in this step we have configuared chrome selenium web driver. so, required chromedriver.exe fie. Add this exe file as executable path and ready for further web scraping techniques.

### Download link for chrome driver exe file :
https://chromedriver.storage.googleapis.com/index.html?path=104.0.5112.29/

### website link address :
https://www.indeed.com/q-data-scientist-jobs.html

In [3]:
from selenium.webdriver.chrome.options import Options
options = Options()
options.headless = True
options.add_argument("--window-size=1920,1200")
search_query_page = 'https://www.indeed.com/q-data-scientist-jobs.html'
driver_path='F:/cli/Data_science_projects/webScrapping/selenium/chromedriver.exe'
driver_chrome_bar = webdriver.Chrome(executable_path=driver_path)
driver_chrome_bar.get(search_query_page)
driver_chrome_bar.maximize_window()
#print("===print the page sources===",driver_chrome_bar.page_source)
time.sleep(5)

C:\Users\USER\AppData\Local\Temp/ipykernel_2292/3511497003.py:7: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver_chrome_bar = webdriver.Chrome(executable_path=driver_path)

#### Before going to the web scraping detailing, wejust check its syntax and how to target element through X_path

In [4]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
job_list = driver_chrome_bar.find_element(By.XPATH,"//div[@class='job_seen_beacon']")
job_list

element = job_list.find_element(by=By.XPATH, value="//h2//a//span")
print(type(job_list))
print(element.get_attribute('innerHTML'))
print(job_list)

<class 'selenium.webdriver.remote.webelement.WebElement'>
Data Scientist 2
<selenium.webdriver.remote.webelement.WebElement (session="505202a67f5c8fc9b0c366e02c999358", element="3d1ae04c-6788-430f-af67-bfe55a73495d")>

### Scrape data from the web-page from various web element and stored into an array :

In [5]:
job_details = []
job_info = []

#list of all jobs with their elements
job_list = driver_chrome_bar.find_elements(By.XPATH,"//div[@class='job_seen_beacon']")
#job_list = driver_chrome_bar.find_elements(By.XPATH,"//div[@class='job_seen_beacon']")
for jobx in job_list:
    title = jobx.find_elements(By.XPATH,".//div/h2//span")[0]
    company=jobx.find_elements(By.XPATH,".//div[@class='heading6 company_location tapItem-gutter companyInfo']//span[@class='companyName']")[0]
    location= jobx.find_elements(By.XPATH,".//div[@class='companyLocation']")[0]
    posting_date = jobx.find_elements(By.XPATH,".//span[@class='date']")[0]
    summary = jobx.find_elements(By.XPATH,".//div[@class='job-snippet']")[0]
    job_info = [title.text, company.text, location.text, summary.text, posting_date.text]
    job_details.append(job_info)
#print("====check what inside the job details array=====",job_details)

### construct the dataframe after first page web scraping :

In [6]:
dataframe = pd.DataFrame(job_details, columns= ['Job Title', 'Company', 'Location', 'Summary', 'Posting Date'])
dataframe

,Job Title,Company,Location,Summary,Posting Date
0,Data Scientist 2,The Coca-Cola Company,"Plano, TX 75024",You will play a critical role in the growing D...,Posted\nPosted 8 days ago
1,Junior Data Scientist,Augray,"Remote in Brookfield, WI","Exposure to writing code (Python preferred, R ...",Posted\nPosted 16 days ago
2,Data Scientist,Source Enterprises,"New York, NY 10036 \n(Midtown area)",Stay current on modern trends and advances in ...,Posted\nPosted 30+ days ago
3,Data Scientist I,MasterCard,"Hybrid remote in O'Fallon, MO 63368",Strategic thinker with ability to derive and t...,Posted\nPosted 2 days ago
4,Data Scientist,Scripps Health,"San Diego, CA 92121",Lead internal teams for interdepartmental ende...,Posted\nPosted 2 days ago
5,Data Scientist,Stanislaus County,"Stanislaus County, CA","Identify what data are available and relevant,...",Posted\nPosted 20 days ago
6,Data Scientist (Junior),BDSA,"Remote in Louisville, CO","For example, combining public weather data wit...",Posted\nPosted 30+ days ago
7,Data Scientist,Parsons,"Columbia, MD\n+6 locations",Apply machine learning techniques to identify ...,Posted\nPosted 16 days ago
8,Data Scientist,Leading Solutions LLC,"Wright-Patterson AFB, OH 45324","Shall be tasked with developing, deploying and...",Posted\nPosted 3 days ago
9,Data Scientist - 4373458,Accenture,"San Francisco, CA\n+80 locations","Apply expertise in quantitative analysis, data...",Posted\nPosted 8 days ago
10,Data Scientist,Protection Engineering Consultants,"Central, TX",Preferred areas of expertise include data engi...,Posted\nPosted 30+ days ago
11,Junior Data Scientist,Acima,"Remote in Draper, UT 84020",We are looking for a developing data scientist...,Posted\nPosted 9 days ago
12,Data Scientist,Love's Travel Stops & Country Stores,"Oklahoma City, OK 73120","Utilize statistical languages (R, Python, SAS)...",Posted\nToday
13,Data Scientist,Data Xpander,"Irving, TX","They need to have statistical, mathematical, p...",Posted\nPosted 30+ days ago
14,Data Scientist,Johns Hopkins Applied Physics Laboratory,"Laurel, MD 20723\n+6 locations","Primarily apply knowledge in machine learning,...",Posted\nJust posted

### click on the button for next page:

In [7]:
next_page_btn = driver_chrome_bar.find_element(By.CLASS_NAME, 'pn')
next_page_btn.click()
time.sleep(5)

### close the popup:

In [9]:
close_btn= driver_chrome_bar.find_elements(By.XPATH,"//button[@class='icl-CloseButton vjs-x-button-close']")[0]
close_btn.click()

### List of all jobs with their elements for the next page and stored object in final job details array :

In [10]:
#list of all jobs with their elements
job_list = driver_chrome_bar.find_elements(By.XPATH,"//div[@class='job_seen_beacon']")
#job_list = driver_chrome_bar.find_elements(By.XPATH,"//div[@class='job_seen_beacon']")
for jobx in job_list:
    title = jobx.find_elements(By.XPATH,".//div/h2//span")[0]
    company=jobx.find_elements(By.XPATH,".//div[@class='heading6 company_location tapItem-gutter companyInfo']//span[@class='companyName']")[0]
    location= jobx.find_elements(By.XPATH,".//div[@class='companyLocation']")[0]
    posting_date = jobx.find_elements(By.XPATH,".//span[@class='date']")[0]
    summary = jobx.find_elements(By.XPATH,".//div[@class='job-snippet']")[0]
    job_info = [title.text, company.text, location.text, summary.text, posting_date.text]
    job_details.append(job_info)
#print("===final job details array===",job_details)

### construct the final dataframe:

In [11]:
final_df = pd.DataFrame(job_details, columns= ['Job Title', 'Company', 'Location', 'Summary', 'Posting Date'])

### close the driver:

In [12]:
driver_chrome_bar.quit()

### Display the dataframe :
you can also hide your index value via .hide_index()

In [13]:
final_df.style.background_gradient().set_properties(**{'border': '1px dashed green',
                          'color': '#000'}).set_caption("Web Scraping via chrome web driver")

### calculate current date and append with xlsx file :

In [14]:
from datetime import date
current_date_append = date.today().strftime("%b-%d-%Y")
current_date_append

'Jul-15-2022'

### Save the data to Excel File:

In [15]:
final_df.to_excel('Indeed_DataScientist_Job_role_location-'+current_date_append+'.xlsx', index= False)